### ISSUE TITLE
[0.2.3] Error creating recipes to burn fluids that don't have an order

### ISSUE THREAD

**Issue by randomdud3** [Klonan/KS_Power#6]
With the new iterative approach to create the burning fuel recipes, some of those fuels (modded ones like the ones used on seablock, methanol) don't have that proprerty. I have changed it to use either the order or the name in my local version and it stopped raising errors

Also, on a sidenote, crude-oil used to be burnable, but it doesn't have fuel_value by itself, so with this approach you have effectively removed it as recipe, which is making latest seablock to fail. It does also fail as the new recipes are added on final-fixes, while seablock modifies them on updates

**Comment by Klonan** [comment]
Thanks for the notice, I fixed both

Added a fuel value for crude too, and moved the dynamic stuff to data-updates instead of final-fixes
