### ISSUE TITLE
Turbine logic.

### ISSUE THREAD

**Issue by Ranakastrasz** [Klonan/KS_Power#7]
`if v ~= nil then
      if nv > v then
        dv = (nv-v)/45
        s.wind_speed = v + dv
      end
      
      if nv < v then
        dv = (v-nv)/45
        s.wind_speed = v - dv
      end
    end`

So far as I can determine, there is no difference between the two.  Both evaluate to the same amount.
Either way,
`s.wind_speed = v + ((nv-v)/45)`

```
   if nv > v then
        dv = (nv-v)/45
        s.wind_speed = v + dv
      end
      
      if nv < v then
        dv = (v-nv)/45
        s.wind_speed = v - dv
      end
-- First if
dv = (nv-v)/45
v = v+dv
-- Second if
dv = (v-nv)/45
v = v-dv

-- First If again
dv = (nv-v)/45
v = v+dv

-- Simplified
v = v + ((nv-v)/45)


-- Second If Again
dv = (v-nv)/45
v = v  -dv

-- Simplified.
v = v - (v-nv)/45)
v = v + (-v -(-nv)/45)
v = v + ((-v + nv)/45)
v = v + ((nv-v)/45)
```

Also, to a lesser extent, It looks like if you remove a turbine, the array does not shrink, so it kinda leaks.

**Comment by Ranakastrasz** [comment]
Just simply the whole thing to 

> dv = (nv-v)/45
s.wind_speed = v + dv

**Comment by Klonan** [comment]
Ok I fixed it
