### ISSUE TITLE
Error with burn-recipes only looking for icon and not icons property

### ISSUE THREAD

**Issue by LovelySanta** [Klonan/KS_Power#9]
Hi,

I just found a small bug in KS_powr when loading the mod, together with other mods.
```
115.471 Error ModManager.cpp:1024: Error while loading recipe prototype "burn-high-pressure-liquid-fuel" (recipe): Key "icon" not found in property tree at ROOT.recipe.burn-high-pressure-liquid-fuel.icons[0]
Modifications: KS Power
 116.217 Loaded shader file C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/graphics/shaders/game.cso
 116.217 Loaded shader file C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/graphics/shaders/zoom-to-world.cso
 116.217 Loaded shader file C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/graphics/shaders/alpha-mask.cso
 116.219 Initial atlas bitmap size is 16384
 116.219 Created atlas bitmap 291x5 [none]
 116.219 Created atlas bitmap 132x24 [no-crop, trilinear-filtering, icon, light]
 116.245 Sprites loaded
 116.245 Convert atlas 132x24 to: trilinear-filtering 
 116.251 Custom inputs active: 0
 116.252 Factorio initialised
 116.253 Mods to disable:Failed to load mods: Error while loading recipe prototype "burn-high-pressure-liquid-fuel" (recipe): Key "icon" not found in property tree at ROOT.recipe.burn-high-pressure-liquid-fuel.icons[0]
```

The [Pressurized fluids](https://mods.factorio.com/mod/CompressedFluids) mod [uses the icons property](https://github.com/LovelySanta/FactorioMod-OtherSmallMods/blob/master/CompressedFluids/prototypes/fluid/compressor-fluid.lua#L9-L24) instead of the icon property. This causes [https://github.com/Klonan/KS_Power/blob/master/data-updates.lua#L72](https://github.com/Klonan/KS_Power/blob/master/data-updates.lua#L72) to error becose it is only checking for icon and not for icons.

As sollution I would suggest the same approach as I used: if icon is present, convert it to icons, and then add the extra layer to the icons property no mather what.

Kind regards,
lovely_santa

**Comment by Klonan** [comment]
Should be fixed now
